using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace EmailService.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "EmailTemplates",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Language = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    Subject = table.Column<string>(type: "text", nullable: false),
                    Body = table.Column<string>(type: "text", nullable: false),
                    Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    UpdatedBy = table.Column<string>(type: "text", nullable: true),
                    DeletedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EmailTemplates", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "EmailTemplates",
                columns: new[] { "Id", "Body", "CreatedAt", "DeletedAt", "Description", "IsActive", "Language", "Name", "Subject", "UpdatedAt", "UpdatedBy" },
                values: new object[,]
                {
                    { 1, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Verify Your Email</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Please verify your email address by clicking the link below:</p>\n    <p><a href=\"{{VerifyLink}}\">Verify Email</a></p>\n    <p>If you didn't create an account, please ignore this email.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9100), null, "Template for email verification", true, "en", "verify-email", "Verify Your Email Address", null, null },
                    { 2, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Xác thực Email</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Vui lòng xác thực địa chỉ email của bạn bằng cách nhấp vào liên kết dưới đây:</p>\n    <p><a href=\"{{VerifyLink}}\">Xác thực Email</a></p>\n    <p>Nếu bạn không tạo tài khoản, vui lòng bỏ qua email này.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9120), null, "Template cho xác thực email", true, "vi", "verify-email", "Xác thực địa chỉ email của bạn", null, null },
                    { 3, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>メール確認</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>以下のリンクをクリックしてメールアドレスを確認してください：</p>\n    <p><a href=\"{{VerifyLink}}\">メール確認</a></p>\n    <p>アカウントを作成していない場合は、このメールを無視してください。</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9130), null, "メール確認用テンプレート", true, "ja", "verify-email", "メールアドレスの確認", null, null },
                    { 4, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Reset Password</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>You requested a password reset for your account.</p>\n    <p>Click the link below to reset your password:</p>\n    <p><a href=\"{{ResetLink}}\">Reset Password</a></p>\n    <p>This link will expire in {{ExpiryMinutes}} minutes.</p>\n    <p>If you didn't request this, please ignore this email.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9160), null, "Template for password reset", true, "en", "reset-password", "Reset Your Password", null, null },
                    { 5, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Đặt lại mật khẩu</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Bạn đã yêu cầu đặt lại mật khẩu cho tài khoản của mình.</p>\n    <p>Nhấp vào liên kết dưới đây để đặt lại mật khẩu:</p>\n    <p><a href=\"{{ResetLink}}\">Đặt lại mật khẩu</a></p>\n    <p>Liên kết này sẽ hết hạn sau {{ExpiryMinutes}} phút.</p>\n    <p>Nếu bạn không yêu cầu điều này, vui lòng bỏ qua email này.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9170), null, "Template cho đặt lại mật khẩu", true, "vi", "reset-password", "Đặt lại mật khẩu của bạn", null, null },
                    { 6, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>パスワードリセット</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>アカウントのパスワードリセットをリクエストしました。</p>\n    <p>以下のリンクをクリックしてパスワードをリセットしてください：</p>\n    <p><a href=\"{{ResetLink}}\">パスワードリセット</a></p>\n    <p>このリンクは{{ExpiryMinutes}}分後に期限切れになります。</p>\n    <p>リクエストしていない場合は、このメールを無視してください。</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9190), null, "パスワードリセット用テンプレート", true, "ja", "reset-password", "パスワードのリセット", null, null },
                    { 7, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Password Changed</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your password has been changed successfully.</p>\n    <p>If you didn't make this change, please contact support immediately.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9200), null, "Template for password change confirmation", true, "en", "change-password", "Password Changed Successfully", null, null },
                    { 8, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Mật khẩu đã thay đổi</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Mật khẩu của bạn đã được thay đổi thành công.</p>\n    <p>Nếu bạn không thực hiện thay đổi này, vui lòng liên hệ hỗ trợ ngay lập tức.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9210), null, "Template cho xác nhận thay đổi mật khẩu", true, "vi", "change-password", "Mật khẩu đã được thay đổi thành công", null, null },
                    { 9, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>パスワード変更</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>パスワードが正常に変更されました。</p>\n    <p>この変更を行っていない場合は、すぐにサポートにお問い合わせください。</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9220), null, "パスワード変更確認用テンプレート", true, "ja", "change-password", "パスワードが正常に変更されました", null, null },
                    { 10, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Account Deactivated</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your account has been deactivated.</p>\n    <p>If you have any questions, please contact support.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9230), null, "Template for account deactivation", true, "en", "deactivate-account", "Account Deactivated", null, null },
                    { 11, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tài khoản đã bị vô hiệu hóa</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tài khoản của bạn đã bị vô hiệu hóa.</p>\n    <p>Nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ hỗ trợ.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9240), null, "Template cho vô hiệu hóa tài khoản", true, "vi", "deactivate-account", "Tài khoản đã bị vô hiệu hóa", null, null },
                    { 12, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>アカウント無効化</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>アカウントが無効化されました。</p>\n    <p>ご不明な点がございましたら、サポートにお問い合わせください。</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9250), null, "アカウント無効化用テンプレート", true, "ja", "deactivate-account", "アカウントが無効化されました", null, null },
                    { 13, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Welcome</title>\n</head>\n<body>\n    <h2>Welcome {{Username}}!</h2>\n    <p>Thank you for registering with Google.</p>\n    <p>Your account has been created successfully.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9260), null, "Template for Google registration", true, "en", "register-google", "Welcome to Our Service", null, null },
                    { 14, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Chào mừng</title>\n</head>\n<body>\n    <h2>Chào mừng {{Username}}!</h2>\n    <p>Cảm ơn bạn đã đăng ký bằng Google.</p>\n    <p>Tài khoản của bạn đã được tạo thành công.</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9270), null, "Template cho đăng ký Google", true, "vi", "register-google", "Chào mừng đến với dịch vụ của chúng tôi", null, null },
                    { 15, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ようこそ</title>\n</head>\n<body>\n    <h2>{{Username}}様、ようこそ！</h2>\n    <p>Googleでご登録いただき、ありがとうございます。</p>\n    <p>アカウントが正常に作成されました。</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9280), null, "Google登録用テンプレート", true, "ja", "register-google", "サービスへようこそ", null, null },
                    { 16, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Account Restored</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your account has been restored successfully.</p>\n    <p>Restored at: {{RestoredAt}}</p>\n    <p>Reason: {{Reason}}</p>\n    <p><a href=\"{{LoginUrl}}\">Login to your account</a></p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9290), null, "Template for account restoration", true, "en", "restore-account", "Account Restored", null, null },
                    { 17, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tài khoản đã được khôi phục</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tài khoản của bạn đã được khôi phục thành công.</p>\n    <p>Khôi phục lúc: {{RestoredAt}}</p>\n    <p>Lý do: {{Reason}}</p>\n    <p><a href=\"{{LoginUrl}}\">Đăng nhập vào tài khoản của bạn</a></p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9300), null, "Template cho khôi phục tài khoản", true, "vi", "restore-account", "Tài khoản đã được khôi phục", null, null },
                    { 18, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>アカウント復元</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>アカウントが正常に復元されました。</p>\n    <p>復元日時: {{RestoredAt}}</p>\n    <p>理由: {{Reason}}</p>\n    <p><a href=\"{{LoginUrl}}\">アカウントにログイン</a></p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9310), null, "アカウント復元用テンプレート", true, "ja", "restore-account", "アカウントが復元されました", null, null },
                    { 19, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>File Uploaded</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your file has been uploaded successfully.</p>\n    <p><strong>File Details:</strong></p>\n    <ul>\n        <li><strong>File Name:</strong> {{FileName}}</li>\n        <li><strong>File Size:</strong> {{FileSize}}</li>\n        <li><strong>Upload Time:</strong> {{UploadTime}}</li>\n        <li><strong>IP Address:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Thank you for using our service!</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9320), null, "Template for file upload notification", true, "en", "file-upload", "File Uploaded Successfully", null, null },
                    { 20, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tệp đã được tải lên</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tệp của bạn đã được tải lên thành công.</p>\n    <p><strong>Chi tiết tệp:</strong></p>\n    <ul>\n        <li><strong>Tên tệp:</strong> {{FileName}}</li>\n        <li><strong>Kích thước:</strong> {{FileSize}}</li>\n        <li><strong>Thời gian tải lên:</strong> {{UploadTime}}</li>\n        <li><strong>Địa chỉ IP:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9330), null, "Template cho thông báo tải tệp lên", true, "vi", "file-upload", "Tệp đã được tải lên thành công", null, null },
                    { 21, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ファイルアップロード完了</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>ファイルのアップロードが正常に完了しました。</p>\n    <p><strong>ファイル詳細:</strong></p>\n    <ul>\n        <li><strong>ファイル名:</strong> {{FileName}}</li>\n        <li><strong>ファイルサイズ:</strong> {{FileSize}}</li>\n        <li><strong>アップロード時刻:</strong> {{UploadTime}}</li>\n        <li><strong>IPアドレス:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>サービスをご利用いただき、ありがとうございます！</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9340), null, "ファイルアップロード通知用テンプレート", true, "ja", "file-upload", "ファイルのアップロードが完了しました", null, null },
                    { 22, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>File Downloaded</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your file has been downloaded successfully.</p>\n    <p><strong>File Details:</strong></p>\n    <ul>\n        <li><strong>File Name:</strong> {{FileName}}</li>\n        <li><strong>File Size:</strong> {{FileSize}}</li>\n        <li><strong>Download Time:</strong> {{DownloadTime}}</li>\n        <li><strong>IP Address:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Thank you for using our service!</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9350), null, "Template for file download notification", true, "en", "file-download", "File Downloaded Successfully", null, null },
                    { 23, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tệp đã được tải xuống</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tệp của bạn đã được tải xuống thành công.</p>\n    <p><strong>Chi tiết tệp:</strong></p>\n    <ul>\n        <li><strong>Tên tệp:</strong> {{FileName}}</li>\n        <li><strong>Kích thước:</strong> {{FileSize}}</li>\n        <li><strong>Thời gian tải xuống:</strong> {{DownloadTime}}</li>\n        <li><strong>Địa chỉ IP:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9360), null, "Template cho thông báo tải tệp xuống", true, "vi", "file-download", "Tệp đã được tải xuống thành công", null, null },
                    { 24, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ファイルダウンロード完了</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>ファイルのダウンロードが正常に完了しました。</p>\n    <p><strong>ファイル詳細:</strong></p>\n    <ul>\n        <li><strong>ファイル名:</strong> {{FileName}}</li>\n        <li><strong>ファイルサイズ:</strong> {{FileSize}}</li>\n        <li><strong>ダウンロード時刻:</strong> {{DownloadTime}}</li>\n        <li><strong>IPアドレス:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>サービスをご利用いただき、ありがとうございます！</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9370), null, "ファイルダウンロード通知用テンプレート", true, "ja", "file-download", "ファイルのダウンロードが完了しました", null, null },
                    { 25, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>File Deleted</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your file has been deleted successfully.</p>\n    <p><strong>File Details:</strong></p>\n    <ul>\n        <li><strong>File Name:</strong> {{FileName}}</li>\n        <li><strong>File Size:</strong> {{FileSize}}</li>\n        <li><strong>Delete Time:</strong> {{DeleteTime}}</li>\n        <li><strong>IP Address:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Thank you for using our service!</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9380), null, "Template for file delete notification", true, "en", "file-delete", "File Deleted Successfully", null, null },
                    { 26, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tệp đã được xóa</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tệp của bạn đã được xóa thành công.</p>\n    <p><strong>Chi tiết tệp:</strong></p>\n    <ul>\n        <li><strong>Tên tệp:</strong> {{FileName}}</li>\n        <li><strong>Kích thước:</strong> {{FileSize}}</li>\n        <li><strong>Thời gian xóa:</strong> {{DeleteTime}}</li>\n        <li><strong>Địa chỉ IP:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9390), null, "Template cho thông báo xóa tệp", true, "vi", "file-delete", "Tệp đã được xóa thành công", null, null },
                    { 27, "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ファイル削除完了</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>ファイルの削除が正常に完了しました。</p>\n    <p><strong>ファイル詳細:</strong></p>\n    <ul>\n        <li><strong>ファイル名:</strong> {{FileName}}</li>\n        <li><strong>ファイルサイズ:</strong> {{FileSize}}</li>\n        <li><strong>削除時刻:</strong> {{DeleteTime}}</li>\n        <li><strong>IPアドレス:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>サービスをご利用いただき、ありがとうございます！</p>\n</body>\n</html>", new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9410), null, "ファイル削除通知用テンプレート", true, "ja", "file-delete", "ファイルの削除が完了しました", null, null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_EmailTemplates_Name_Language",
                table: "EmailTemplates",
                columns: new[] { "Name", "Language" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EmailTemplates");
        }
    }
}
