// <auto-generated />
using System;
using EmailService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmailService.Migrations
{
    [DbContext(typeof(EmailServiceDbContext))]
    partial class EmailServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailService.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Language")
                        .IsUnique();

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Verify Your Email</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Please verify your email address by clicking the link below:</p>\n    <p><a href=\"{{VerifyLink}}\">Verify Email</a></p>\n    <p>If you didn't create an account, please ignore this email.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9100),
                            Description = "Template for email verification",
                            IsActive = true,
                            Language = "en",
                            Name = "verify-email",
                            Subject = "Verify Your Email Address"
                        },
                        new
                        {
                            Id = 2,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Xác thực Email</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Vui lòng xác thực địa chỉ email của bạn bằng cách nhấp vào liên kết dưới đây:</p>\n    <p><a href=\"{{VerifyLink}}\">Xác thực Email</a></p>\n    <p>Nếu bạn không tạo tài khoản, vui lòng bỏ qua email này.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9120),
                            Description = "Template cho xác thực email",
                            IsActive = true,
                            Language = "vi",
                            Name = "verify-email",
                            Subject = "Xác thực địa chỉ email của bạn"
                        },
                        new
                        {
                            Id = 3,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>メール確認</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>以下のリンクをクリックしてメールアドレスを確認してください：</p>\n    <p><a href=\"{{VerifyLink}}\">メール確認</a></p>\n    <p>アカウントを作成していない場合は、このメールを無視してください。</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9130),
                            Description = "メール確認用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "verify-email",
                            Subject = "メールアドレスの確認"
                        },
                        new
                        {
                            Id = 4,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Reset Password</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>You requested a password reset for your account.</p>\n    <p>Click the link below to reset your password:</p>\n    <p><a href=\"{{ResetLink}}\">Reset Password</a></p>\n    <p>This link will expire in {{ExpiryMinutes}} minutes.</p>\n    <p>If you didn't request this, please ignore this email.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9160),
                            Description = "Template for password reset",
                            IsActive = true,
                            Language = "en",
                            Name = "reset-password",
                            Subject = "Reset Your Password"
                        },
                        new
                        {
                            Id = 5,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Đặt lại mật khẩu</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Bạn đã yêu cầu đặt lại mật khẩu cho tài khoản của mình.</p>\n    <p>Nhấp vào liên kết dưới đây để đặt lại mật khẩu:</p>\n    <p><a href=\"{{ResetLink}}\">Đặt lại mật khẩu</a></p>\n    <p>Liên kết này sẽ hết hạn sau {{ExpiryMinutes}} phút.</p>\n    <p>Nếu bạn không yêu cầu điều này, vui lòng bỏ qua email này.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9170),
                            Description = "Template cho đặt lại mật khẩu",
                            IsActive = true,
                            Language = "vi",
                            Name = "reset-password",
                            Subject = "Đặt lại mật khẩu của bạn"
                        },
                        new
                        {
                            Id = 6,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>パスワードリセット</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>アカウントのパスワードリセットをリクエストしました。</p>\n    <p>以下のリンクをクリックしてパスワードをリセットしてください：</p>\n    <p><a href=\"{{ResetLink}}\">パスワードリセット</a></p>\n    <p>このリンクは{{ExpiryMinutes}}分後に期限切れになります。</p>\n    <p>リクエストしていない場合は、このメールを無視してください。</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9190),
                            Description = "パスワードリセット用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "reset-password",
                            Subject = "パスワードのリセット"
                        },
                        new
                        {
                            Id = 7,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Password Changed</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your password has been changed successfully.</p>\n    <p>If you didn't make this change, please contact support immediately.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9200),
                            Description = "Template for password change confirmation",
                            IsActive = true,
                            Language = "en",
                            Name = "change-password",
                            Subject = "Password Changed Successfully"
                        },
                        new
                        {
                            Id = 8,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Mật khẩu đã thay đổi</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Mật khẩu của bạn đã được thay đổi thành công.</p>\n    <p>Nếu bạn không thực hiện thay đổi này, vui lòng liên hệ hỗ trợ ngay lập tức.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9210),
                            Description = "Template cho xác nhận thay đổi mật khẩu",
                            IsActive = true,
                            Language = "vi",
                            Name = "change-password",
                            Subject = "Mật khẩu đã được thay đổi thành công"
                        },
                        new
                        {
                            Id = 9,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>パスワード変更</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>パスワードが正常に変更されました。</p>\n    <p>この変更を行っていない場合は、すぐにサポートにお問い合わせください。</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9220),
                            Description = "パスワード変更確認用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "change-password",
                            Subject = "パスワードが正常に変更されました"
                        },
                        new
                        {
                            Id = 10,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Account Deactivated</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your account has been deactivated.</p>\n    <p>If you have any questions, please contact support.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9230),
                            Description = "Template for account deactivation",
                            IsActive = true,
                            Language = "en",
                            Name = "deactivate-account",
                            Subject = "Account Deactivated"
                        },
                        new
                        {
                            Id = 11,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tài khoản đã bị vô hiệu hóa</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tài khoản của bạn đã bị vô hiệu hóa.</p>\n    <p>Nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ hỗ trợ.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9240),
                            Description = "Template cho vô hiệu hóa tài khoản",
                            IsActive = true,
                            Language = "vi",
                            Name = "deactivate-account",
                            Subject = "Tài khoản đã bị vô hiệu hóa"
                        },
                        new
                        {
                            Id = 12,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>アカウント無効化</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>アカウントが無効化されました。</p>\n    <p>ご不明な点がございましたら、サポートにお問い合わせください。</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9250),
                            Description = "アカウント無効化用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "deactivate-account",
                            Subject = "アカウントが無効化されました"
                        },
                        new
                        {
                            Id = 13,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Welcome</title>\n</head>\n<body>\n    <h2>Welcome {{Username}}!</h2>\n    <p>Thank you for registering with Google.</p>\n    <p>Your account has been created successfully.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9260),
                            Description = "Template for Google registration",
                            IsActive = true,
                            Language = "en",
                            Name = "register-google",
                            Subject = "Welcome to Our Service"
                        },
                        new
                        {
                            Id = 14,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Chào mừng</title>\n</head>\n<body>\n    <h2>Chào mừng {{Username}}!</h2>\n    <p>Cảm ơn bạn đã đăng ký bằng Google.</p>\n    <p>Tài khoản của bạn đã được tạo thành công.</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9270),
                            Description = "Template cho đăng ký Google",
                            IsActive = true,
                            Language = "vi",
                            Name = "register-google",
                            Subject = "Chào mừng đến với dịch vụ của chúng tôi"
                        },
                        new
                        {
                            Id = 15,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ようこそ</title>\n</head>\n<body>\n    <h2>{{Username}}様、ようこそ！</h2>\n    <p>Googleでご登録いただき、ありがとうございます。</p>\n    <p>アカウントが正常に作成されました。</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9280),
                            Description = "Google登録用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "register-google",
                            Subject = "サービスへようこそ"
                        },
                        new
                        {
                            Id = 16,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Account Restored</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your account has been restored successfully.</p>\n    <p>Restored at: {{RestoredAt}}</p>\n    <p>Reason: {{Reason}}</p>\n    <p><a href=\"{{LoginUrl}}\">Login to your account</a></p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9290),
                            Description = "Template for account restoration",
                            IsActive = true,
                            Language = "en",
                            Name = "restore-account",
                            Subject = "Account Restored"
                        },
                        new
                        {
                            Id = 17,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tài khoản đã được khôi phục</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tài khoản của bạn đã được khôi phục thành công.</p>\n    <p>Khôi phục lúc: {{RestoredAt}}</p>\n    <p>Lý do: {{Reason}}</p>\n    <p><a href=\"{{LoginUrl}}\">Đăng nhập vào tài khoản của bạn</a></p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9300),
                            Description = "Template cho khôi phục tài khoản",
                            IsActive = true,
                            Language = "vi",
                            Name = "restore-account",
                            Subject = "Tài khoản đã được khôi phục"
                        },
                        new
                        {
                            Id = 18,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>アカウント復元</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>アカウントが正常に復元されました。</p>\n    <p>復元日時: {{RestoredAt}}</p>\n    <p>理由: {{Reason}}</p>\n    <p><a href=\"{{LoginUrl}}\">アカウントにログイン</a></p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9310),
                            Description = "アカウント復元用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "restore-account",
                            Subject = "アカウントが復元されました"
                        },
                        new
                        {
                            Id = 19,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>File Uploaded</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your file has been uploaded successfully.</p>\n    <p><strong>File Details:</strong></p>\n    <ul>\n        <li><strong>File Name:</strong> {{FileName}}</li>\n        <li><strong>File Size:</strong> {{FileSize}}</li>\n        <li><strong>Upload Time:</strong> {{UploadTime}}</li>\n        <li><strong>IP Address:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Thank you for using our service!</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9320),
                            Description = "Template for file upload notification",
                            IsActive = true,
                            Language = "en",
                            Name = "file-upload",
                            Subject = "File Uploaded Successfully"
                        },
                        new
                        {
                            Id = 20,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tệp đã được tải lên</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tệp của bạn đã được tải lên thành công.</p>\n    <p><strong>Chi tiết tệp:</strong></p>\n    <ul>\n        <li><strong>Tên tệp:</strong> {{FileName}}</li>\n        <li><strong>Kích thước:</strong> {{FileSize}}</li>\n        <li><strong>Thời gian tải lên:</strong> {{UploadTime}}</li>\n        <li><strong>Địa chỉ IP:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9330),
                            Description = "Template cho thông báo tải tệp lên",
                            IsActive = true,
                            Language = "vi",
                            Name = "file-upload",
                            Subject = "Tệp đã được tải lên thành công"
                        },
                        new
                        {
                            Id = 21,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ファイルアップロード完了</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>ファイルのアップロードが正常に完了しました。</p>\n    <p><strong>ファイル詳細:</strong></p>\n    <ul>\n        <li><strong>ファイル名:</strong> {{FileName}}</li>\n        <li><strong>ファイルサイズ:</strong> {{FileSize}}</li>\n        <li><strong>アップロード時刻:</strong> {{UploadTime}}</li>\n        <li><strong>IPアドレス:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>サービスをご利用いただき、ありがとうございます！</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9340),
                            Description = "ファイルアップロード通知用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "file-upload",
                            Subject = "ファイルのアップロードが完了しました"
                        },
                        new
                        {
                            Id = 22,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>File Downloaded</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your file has been downloaded successfully.</p>\n    <p><strong>File Details:</strong></p>\n    <ul>\n        <li><strong>File Name:</strong> {{FileName}}</li>\n        <li><strong>File Size:</strong> {{FileSize}}</li>\n        <li><strong>Download Time:</strong> {{DownloadTime}}</li>\n        <li><strong>IP Address:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Thank you for using our service!</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9350),
                            Description = "Template for file download notification",
                            IsActive = true,
                            Language = "en",
                            Name = "file-download",
                            Subject = "File Downloaded Successfully"
                        },
                        new
                        {
                            Id = 23,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tệp đã được tải xuống</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tệp của bạn đã được tải xuống thành công.</p>\n    <p><strong>Chi tiết tệp:</strong></p>\n    <ul>\n        <li><strong>Tên tệp:</strong> {{FileName}}</li>\n        <li><strong>Kích thước:</strong> {{FileSize}}</li>\n        <li><strong>Thời gian tải xuống:</strong> {{DownloadTime}}</li>\n        <li><strong>Địa chỉ IP:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9360),
                            Description = "Template cho thông báo tải tệp xuống",
                            IsActive = true,
                            Language = "vi",
                            Name = "file-download",
                            Subject = "Tệp đã được tải xuống thành công"
                        },
                        new
                        {
                            Id = 24,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ファイルダウンロード完了</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>ファイルのダウンロードが正常に完了しました。</p>\n    <p><strong>ファイル詳細:</strong></p>\n    <ul>\n        <li><strong>ファイル名:</strong> {{FileName}}</li>\n        <li><strong>ファイルサイズ:</strong> {{FileSize}}</li>\n        <li><strong>ダウンロード時刻:</strong> {{DownloadTime}}</li>\n        <li><strong>IPアドレス:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>サービスをご利用いただき、ありがとうございます！</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9370),
                            Description = "ファイルダウンロード通知用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "file-download",
                            Subject = "ファイルのダウンロードが完了しました"
                        },
                        new
                        {
                            Id = 25,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>File Deleted</title>\n</head>\n<body>\n    <h2>Hello {{Username}},</h2>\n    <p>Your file has been deleted successfully.</p>\n    <p><strong>File Details:</strong></p>\n    <ul>\n        <li><strong>File Name:</strong> {{FileName}}</li>\n        <li><strong>File Size:</strong> {{FileSize}}</li>\n        <li><strong>Delete Time:</strong> {{DeleteTime}}</li>\n        <li><strong>IP Address:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Thank you for using our service!</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9380),
                            Description = "Template for file delete notification",
                            IsActive = true,
                            Language = "en",
                            Name = "file-delete",
                            Subject = "File Deleted Successfully"
                        },
                        new
                        {
                            Id = 26,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Tệp đã được xóa</title>\n</head>\n<body>\n    <h2>Xin chào {{Username}},</h2>\n    <p>Tệp của bạn đã được xóa thành công.</p>\n    <p><strong>Chi tiết tệp:</strong></p>\n    <ul>\n        <li><strong>Tên tệp:</strong> {{FileName}}</li>\n        <li><strong>Kích thước:</strong> {{FileSize}}</li>\n        <li><strong>Thời gian xóa:</strong> {{DeleteTime}}</li>\n        <li><strong>Địa chỉ IP:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9390),
                            Description = "Template cho thông báo xóa tệp",
                            IsActive = true,
                            Language = "vi",
                            Name = "file-delete",
                            Subject = "Tệp đã được xóa thành công"
                        },
                        new
                        {
                            Id = 27,
                            Body = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>ファイル削除完了</title>\n</head>\n<body>\n    <h2>{{Username}}様、</h2>\n    <p>ファイルの削除が正常に完了しました。</p>\n    <p><strong>ファイル詳細:</strong></p>\n    <ul>\n        <li><strong>ファイル名:</strong> {{FileName}}</li>\n        <li><strong>ファイルサイズ:</strong> {{FileSize}}</li>\n        <li><strong>削除時刻:</strong> {{DeleteTime}}</li>\n        <li><strong>IPアドレス:</strong> {{IpAddress}}</li>\n    </ul>\n    <p>サービスをご利用いただき、ありがとうございます！</p>\n</body>\n</html>",
                            CreatedAt = new DateTime(2025, 8, 12, 9, 35, 8, 696, DateTimeKind.Utc).AddTicks(9410),
                            Description = "ファイル削除通知用テンプレート",
                            IsActive = true,
                            Language = "ja",
                            Name = "file-delete",
                            Subject = "ファイルの削除が完了しました"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
